### ISSUE TITLE
Project checkpoint 3 ready for review

### ISSUE THREAD

**Issue by misterToo** [misterToo/PizzaWebsite#8]
@pawaitemadisoncollege Project Checkpoint 3 ready for review

**Comment by pawaitemadisoncollege** [comment]
Glad to hear you got Checkpoint 3 items completed @misterToo! 

- [ ] Can you point me to these checkpoint 3 items: "Deployed to AWS, at least one JSP that displays data from the database is implemented, authentication implemented (log in capability).  Please be sure to add your deployed app’s url to the list of individual projects and create an issue when your CP 3 is ready."

**Comment by misterToo** [comment]
Added link to individual projects md file, link in the nav bar for the customer display JSP, auth implemented locally, has some issues I'm working through

**Comment by misterToo** [comment]
http://pizzawebsite-env-1.eba-rrtjj97r.us-east-2.elasticbeanstalk.com/

**Comment by pawaitemadisoncollege** [comment]
Thanks for the updates @misterToo. I'll update blackboard for CP3.

A few things I noticed that are likely on your radar, but I'd be remiss if I didn't mention them here:

- [ ] You have some sensitive files visible on GitHub. May want to remove these, add to GitHub ignore and then re-add. I you have difficulty getting git to "forget" about these files, try a search for how to remove files from git and GitHub. https://github.com/misterToo/PizzaWebsite/blob/main/src/main/.ebextensions/https-instance.config.  
- [ ] Remember to remove entity-specific daos (OrderDAO).  The generic dao should handle everything.
- [ ] Should this title be user-specific? https://github.com/misterToo/PizzaWebsite/blob/aafe112decee9de05007f3d122250e52081e51e1/src/main/webapp/order.jsp#L12
- [ ] Would it make sense to put this bit in its own jsp for easier reuse and maintenance: https://github.com/misterToo/PizzaWebsite/blob/aafe112decee9de05007f3d122250e52081e51e1/src/main/webapp/order.jsp#L16-L46
- [ ] Is this test used/needed? If so, it should test your actual API Client class.https://github.com/misterToo/PizzaWebsite/blob/aafe112decee9de05007f3d122250e52081e51e1/src/test/java/com.mistertoo.pizzawebsite/TestServiceClient.java#L14-L24
- [ ] This class would be better named CustomerDao test (as it is ultimately testing the Customer). 
- [ ] Unit tests should test relationships on the delete - if a customer is deleted, what should happen to the order. If an order is deleted, what should happen to the Customer? Make sure you have tests to verify what should happen, does happen.

**Comment by misterToo** [comment]
Removed mentioned file from github, Auth now deployed on AWS, removed Order-specific DAO

**Comment by pawaitemadisoncollege** [comment]
Nice job getting auth working! CP3 = Done!
